### ISSUE TITLE
Add WebGL fallback

### ISSUE THREAD

**Issue by peq42** [mlc-ai/web-llm#229]
WebGPU is nowhere nearly as widely adopted as webgl 1 and 2. This means that maybe 15% of people out there with internet connection can run the project. I myself am using the latest version of Firefox and I can't run it!

There should be some sort of fallback to webgl when webgpu isn't detected. Otherwise, the project won't be useable for at least a solid 5+ years until webGPU adoption grows enough

**Comment by tqchen** [comment]
Unfirtunately WebGL's programming model is limited and cannot enable some fo the optimizations needed.

Good news is that Firefox is also working to land WebGPU https://bugzilla.mozilla.org/show_bug.cgi?id=1841346

**Comment by DavidGOrtega** [comment]
WebGL is not worth at all for simple reasons as culling. 
WEBGPU is the way to go and will be greater when we move out the webassembly 4GB cage.


Totally out of topic. @tqchen did you had a chance to review TVM with wgpu?

**Comment by peq42** [comment]
> WebGL is not worth at all for simple reasons like culling. WEBGPU is the way to go and will be greater when we move out the webassembly 4GB cage.
> 
> Totally out of topic. @tqchen did you had a chance to review TVM with wgpu?

ah yes, nothing like buying a car you can't drive anywhere because the roads dont support it. 

Makes for a beautiful paper weight

**Comment by DavidGOrtega** [comment]
> WebGPU isn't supported by most browsers

Can you name a few? 

Chromium based browsers supports WebGPU right now. To name a few Chrome, Opera, Edge and of course and the most important Electron... When I say supported is that it comes enabled by default not  having to enable the flag. Safari and others supports it with the flag.

Everybody is moving from WebGL because of (sight) many issues, only float16, culling... almost every single framework do not support all the operators thats why wasm has succeded, and of course the effort... Its simply not worth at this point.

**Comment by peq42** [comment]
@DavidGOrtega I meant by most browser versions being currently used. As you can see
https://caniuse.com/webgpu
https://www.stetic.com/market-share/browser/

Only about ~30% of chrome users, ~7% Edge, ~1% of opera, 0% firefox and safari can use webGPU currently. And thats based on the statics of that one website, some others point to even LESS.

Now consider this https://www.khronos.org/blog/webgl-2-achieves-pervasive-support-from-all-major-web-browsers being exactly what I said(took webgl 2 about 5 years to be supported on all browsers, and for most versions being actively used)

**Comment by DavidGOrtega** [comment]
@peq42 stats improves when you watch desktop, for mobile you have to go straight with TVM mobile.

<img width="355" alt="image" src="https://github.com/mlc-ai/web-llm/assets/414967/a7711679-8949-450d-bf8a-95ce38a444af">

And this discussion is a bit of futile, not because Webgpu is supported or not, Its just because WebGL has so many issues that failed to deliver, its simply not the right tool to do DL in the browser. Thats why many operators are not implemented in many frameworks.
I any case, TVM is open source, you can of course contribute and enjoy the unpleasant WebGL way 🙂
