### ISSUE TITLE
Does not work for me on Windows 11 and Chrome Canary

### ISSUE THREAD

**Issue by kohlerm** [mlc-ai/web-llm#28]
Chrome Version 114.0.5715.0 (Official Build) canary (64-bit)

The error is:
mlc.ai/:1 No available adapters.
llm_chat.js:421 Error: Cannot find adapter that matches the request
    at Object.<anonymous> (tvmjs.bundle.js:587:24)
    at Generator.next (<anonymous>)
    at fulfilled (tvmjs.bundle.js:552:59)
llm_chat.js:547 Error: Find an error initializing WebGPU: Error: Cannot find adapter that matches the request
    at #asyncInitTVM (llm_chat.js:423:13)
    at async LLMChatInstance.asyncInit (llm_chat.js:443:5)
    at async LLMChatInstance.generate (llm_chat.js:544:7)

**Comment by zeritonius** [comment]
Could you, please, try the link below and tell me if you see a big red triangle or an error message?
https://webgpu.github.io/webgpu-samples/samples/helloTriangle


![redtriangle](https://user-images.githubusercontent.com/89370810/232849114-3e7fa384-6b10-44d4-9e4a-65c0d48d1c54.png)

**Comment by satellitecomponent** [comment]
I am also having this issue.

On windows 11, Chrome Canary, Laptop, getting this error,
localhost/:1 No available adapters.
webllm.ts:38 Uncaught (in promise) Error: Cannot find adapter that matches the request

I was able to run web-llm using my intel GPU, and received this error when trying to ensure Canary would use my Nvidia card rather than my CPU. 

While writing this comment I discovered a solution.

on chrome://flags/
enabling 

[#use-angle](chrome://flags/#use-angle)

setting this flag to D3D11 allowed for me to use my GPU.

Finish loading on WebGPU - NVIDIA GeForce RTX 2070 with Max-Q Design

I also have these flags enabled. Not all of them may be necessary.
[#enable-webgpu-developer-features](chrome://flags/#enable-webgpu-developer-features)
[#enable-unsafe-webgpu](chrome://flags/#enable-unsafe-webgpu)
[#ignore-gpu-blocklist](chrome://flags/#ignore-gpu-blocklist)


The chat is now a lot faster. (of course!)
