### ISSUE TITLE
Chrome demo frequently terminates while loading

### ISSUE THREAD

**Issue by neubig** [mlc-ai/web-llm#322]
Thank you for the great project! I'm playing with the chrome extension. It works some of the time, but it also frequently (>50% of the time) dies while loading the model. The progress bar stops half-way through, and this is what I see in the console when I inspect the plugin popup:

![Screenshot 2024-02-29 at 8 45 24 AM](https://github.com/mlc-ai/web-llm/assets/398875/30b2a74f-ef4b-4713-9463-ee97cff752d6)

I'm using:
* Chrome: Version 122.0.6261.94 (Official Build) (arm64)
* web-llm: ab26e65f483c58a9f410e8594d9384f9e08d6d4b

I'm happy to help debug in any way.

**Comment by kudaibergenu** [comment]
I am experiencing the same problem. So far, I understood the problem starts once it tries to pull the models from the cache.

**Comment by CharlieFRuan** [comment]
Apologies for the inconvenience, I'll look into this issue today. Meanwhile, clearing chrome's cache might alleviate the problem.

**Comment by CharlieFRuan** [comment]
@neubig Just updated the npm to 0.2.24: https://github.com/mlc-ai/web-llm/pull/323

This should fix it. Let us know if issues persist. Thank you!

**Comment by neubig** [comment]
Thanks for the fast response @CharlieFRuan !
I upgraded to the latest version and it does seem to not be hanging anymore, so I'll close the issue.

**Comment by mrsheep76** [comment]
I'm still experiencing this issue even after updating to the latest version (0.2.24).

Would you be open to further investigation? Some notes from my own experience:

- It happens 90%+ of the time
- The progress bar usually gets about 70-80% finished before the crash
- Clearing the Chrome cache temporarily fixes the problem, but it begins immediately again on the next reload from cache
- I reproduced it at least once from the "get-started" example (not Chrome extension), but it seems to happen somewhat less often than in the Chrome extension.

Happy to help chase this down - thanks!

**Comment by neubig** [comment]
And actually I'm still encountering crashes as well, although it seems less frequent than before.

**Comment by CharlieFRuan** [comment]
@mrsheep76 @neubig Thanks for the info, I'll look into it today!

**Comment by CharlieFRuan** [comment]
@mrsheep76 @neubig I was not able to replicate the change (either via simple chat or the chrome extension example). But I published 0.2.25, with the hope of fixing this (assuming the issue is due to parallelly downloading too many shards at the same time). For more description, see https://github.com/mlc-ai/web-llm/pull/328. Let me know, thanks!

**Comment by mrsheep76** [comment]
@CharlieFRuan Thanks for the attempted fix! Unfortunately I'm still getting crashes 90%+ of the time when loading from cache -- same frequency as before from what I can tell. It does occasionally work, so I wonder if there's a race condition somewhere?

Is there any way for me to get a more informative error message and pass it to you, since you cannot reproduce it yourself? The `exit(1)` is obviously pretty generic...

**Comment by CharlieFRuan** [comment]
Hmm I see; before we further dig into this, could you perhaps try a smaller model, say Gemma 2B (assuming that you are using Mistral 7B q4f16, the default one in the chrome extension example). Not sure how much RAM you have, but it could be that the model is too large?

**Comment by CharlieFRuan** [comment]
And I just noticed that it states `Loading model from cache` in the log, rather than `Fetching param cache`. This means that all shards of the model parameters are already in the browser cache. Perhaps you can try to clear the cache, and let it fetch the params again. The `Cached images and files` in chrome should do it: 
<img width="518" alt="image" src="https://github.com/mlc-ai/web-llm/assets/53290280/4b0253c5-ac6f-4161-852e-b3649ad87623">

**Comment by CharlieFRuan** [comment]
I also further bumped to 0.2.26, which adds an additional try-catch, attempting to provide more information to the `exit(1)`.

**Comment by neubig** [comment]
Thanks! I tried 4-5 times now, including after clearing cache and every time worked! So maybe this is fixed with the new version. Closing for now, thanks @CharlieFRuan !

**Comment by CharlieFRuan** [comment]
@neubig Thanks for confirming; feel free to reopen any time!

**Comment by mrsheep76** [comment]
Good news - it is now working for me as well!

I had a temporary glitch with my build environment during my last test run, so I suspect one of the earlier fixes actually did the trick (perhaps limiting the number of concurrent threads)?

In any case, it is working consistently now. Thank you for all the help!

**Comment by CharlieFRuan** [comment]
@mrsheep76 Thanks, that is great to hear! Feel free to open new issues if there are other problems
