### ISSUE TITLE
Simple-chat is successfully deployed on the PC, an error occurs：Init error, TypeError: crypto.randomUUlD is not a function when I accesses the web port using the smart phone browser

### ISSUE THREAD

**Issue by lebron8dong** [mlc-ai/web-llm#338]
![image](https://github.com/mlc-ai/web-llm/assets/73160333/03d4421d-5f39-4434-abe5-1a42df8d21d1)

PC：Google canary
phone：Google

**Comment by felladrin** [comment]
It happens because you can't access `crypto` in the browser when running through `http` (insecure context). Note that this rule doesn't apply for `http://localhost` nor `http://127.0.0.1`.
And by your screenshot, you're accessing `http://10.203.161.238`.

Reference: https://developer.mozilla.org/en-US/docs/Web/API/Crypto#usage_notes

> In general, you probably should just treat Crypto as available only on secure contexts.

Possible solutions are:
- Run a local https server - you can use a self-signed certificate.
- Run it through a tunnel, like [localtunnel](https://theboroer.github.io/localtunnel-www/), which gives you an https URL to access your app.

**Comment by CharlieFRuan** [comment]
Ran into the same issue when testing on a mobile device. Using localtunnel like @felladrin suggested worked for me (thanks!).

Alternatively, if you are using an Android testing on Android Chrome, you can try the built-in port forwarding, which lets you access `localhost` directly on the phone, without using an IP address like `10.203.161.238`. See tutorials like [this one](https://raygun.com/blog/debug-android-chrome/).

**Comment by CharlieFRuan** [comment]
Closing this issue for now, as either port forwarding or localtunnel should resolve it. Feel free to reopen if issues persist.
