### ISSUE TITLE
Run llama.cpp models

### ISSUE THREAD

**Issue by MariasStory** [mlc-ai/web-llm#38]
I guess it would be easy for you run the ggml [llama.cpp](https://github.com/ggerganov/llama.cpp) compatible models.
In this case, you don't need the GPU and could run the models in memory.
From a simple test I find that llama.cpp is faster on 13B model then web-llm on 7B model on the same system.
Although, running in GPU migt help:
https://github.com/ggerganov/llama.cpp/discussions/915

**Comment by MariasStory** [comment]
HI,
For running the web-llm in browser I've tried a NVIDIA T2000 and a build in I9 intel GPU.
The T2000 is fast in the prompt ingestion at ~17 tokens/s and slowest in generation ~0.6 tokens/s.
The build in I9 intel GPU was ~2 tokens/s in both tasks.

The llama.cpp runs on a CPU only and it uses speedup tricks like mmap to store the model in memory. But, for the 13B model the memory use is ~7 GB.

**Comment by MariasStory** [comment]
Just out of curiosity, what do you mean by "bringing maximum performance on macbook gpu" is it a limitation of TVM?
Or, you are using some GPU specific tricks?
Any way, there are two parts to my request:
1. First is about CPU execution and the possibility to run ggml models in browser, similar to the way as it is run by llama.cpp.
2. The second is a possibility to run the ggml models with GPU in browser. Similar to the topic of the discussion: https://github.com/ggerganov/llama.cpp/discussions/915

**Comment by jinhongyii** [comment]
For "bringing maximum performance on macbook gpu", you need to know that the same code implementation could have dramatically different performance on different hardwares. So it's impossible to run equally well on all devices. Our choice is to bring best performance for macbook gpu first, and then improve performance on other devices.

For the rest of your question, the answer is sadly "no". The reason is that ggml doesn't have a good enough codegen for webgpu. Even with Triton, it can only codegen for cuda. TVM is designed for deploying on diverse backends, and that's why we choose it as our framework.

But what we can promise is that : we will try to optimize as much as we could so that we could align or outperform llama.cpp on as many devices as possible.
