### ISSUE TITLE
Models output is scrambled in Safari Technology Preview, which has WebGPU support

### ISSUE THREAD

**Issue by felladrin** [mlc-ai/web-llm#386]
Just wanted to inform that I installed [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/) to check its support for WebGPU and I noticed that the output of any model in Web-LLM appears scrambled like this:

<img width="1163" alt="image" src="https://github.com/mlc-ai/web-llm/assets/418083/4595fba9-ec6e-4271-af8d-6ba072f424ea">

<img width="1820" alt="image" src="https://github.com/mlc-ai/web-llm/assets/418083/936fc8af-138f-4421-ad8f-2c968bbe4793">

And sometimes it just repeats the same word:

https://github.com/mlc-ai/web-llm/assets/418083/176653dd-d4a5-4a5a-b950-4b776e7783e2

Although not urgent, it may be worth looking into it before the next major release of Safari.

**Comment by tqchen** [comment]
This is a known issue that we are working with the safari team to address https://bugs.webkit.org/show_bug.cgi?id=266793

**Comment by mwyrzykowski** [comment]
This is working for me in Safari Technology Preview 193: https://developer.apple.com/safari/resources/
![stp193](https://github.com/mlc-ai/web-llm/assets/105083895/c6d6be53-1960-4924-a2cc-b84d68734bfc)

**Comment by mwyrzykowski** [comment]
Safari from the iOS 18 developer betas is still non-functional as it appears web-llm requires 1024MB sized buffers:
![ios18beta](https://github.com/mlc-ai/web-llm/assets/105083895/b5ddd339-71fe-4ff6-9e9c-f5b836d48b11)

The default max buffer size in WebGPU is 256MB. I tried raising the limit to 1024MB but then iOS Safari is terminated due to memory pressure. I filed https://bugs.webkit.org/show_bug.cgi?id=275958 to track that issue

**Comment by mwyrzykowski** [comment]
I'm not sure if this issue should be closed now as it is working on Safari Technology Preview 193 and a new one should be opened for iOS support? 

iOS support is a bit trickier, while everything should 'just work' like an Apple Silicon Mac, if WebLLM really does require a 1GB buffer and allocates a JavaScript array of 1024MB, then this will lead to memory issues on iOS.

It would be preferable if WebLLM can work within the default 256MB buffer size limit of WebGPU, if possible, potentially creating multiple buffers if needed and not creating a JS array buffer greater in size than 256MB at once.

**Comment by tqchen** [comment]
Thank you @mwyrzykowski , this issue can be closed. There are smaller models that we use for smaller context (the models that ends with -1k suffix) that might workd for 256MB limit, as android also has this limit

**Comment by CharlieFRuan** [comment]
Hi @mwyrzykowski, thanks for the support and sorry for the delayed response. WebLLM after npm 0.2.47 should fall back to `maxBufferSize` 256MB in case the 1024MB hits the limit: https://github.com/mlc-ai/web-llm/pull/498

Tried https://chat.webllm.ai/ on my iOS 18 developer beta and it works well; the speed is great too! 

<img src="https://github.com/user-attachments/assets/9997642e-5371-4b44-ba60-81ec8fafa772" width=50% height=50%>

**Comment by mwyrzykowski** [comment]
Oh that is amazing news, thank you so much for the update!

**Comment by tqchen** [comment]
Actually @mwyrzykowski if it is possible to enable iOS to have bigger buffers, it would be nice. Since some of the 3B models can fit well on mobile, and may have 1GB buffer requirements

**Comment by mwyrzykowski** [comment]
> Actually @mwyrzykowski if it is possible to enable iOS to have bigger buffers, it would be nice. Since some of the 3B models can fit well on mobile, and may have 1GB buffer requirements

It is possible but the memory limit per web process is 1.5GB. If we raise it, the website needs to be careful with populating the buffer because both the ArrayBuffer in JavaScript and the buffer allocation within WebGPU count towards that 1.5GB limit. 

The WebGPU specification currently requires we make a copy of the buffer so I don’t think we can directly use the JS allocation. 

In order to use a 1GB buffer you would need to also not allocate a 1GB buffer on the JS side, because at that point you would be at 2GB and the web process would get terminated. Rather the GPUBuffer instance would need to be filled incrementally, like in 128MB chunks or so. That should remain below the memory limit.

**Comment by mwyrzykowski** [comment]
@tqchen is it possible to achieve the same with four 256MB buffers? WebKit’s concern to raising the limit is an arbitrary website may see 1GB and make a 1GB JavaScript ArrayBuffer to fill it. Which will work fine on macOS but not iOS.
