### ISSUE TITLE
Where is the source code for vicuna-7b_webgpu.wasm?

### ISSUE THREAD

**Issue by zeritonius** [mlc-ai/web-llm#40]
Where is the source code for vicuna-7b_webgpu.wasm, please?

Thank you.

**Comment by jinhongyii** [comment]
We will post a tutorial on how to build the model into generated source code, but currently that's not ready until we migrate the vicuna-v0 to vicuna-v1.1 (The reason is that vicuna-v0 is deprecated and it's complicated to get its weight compared with v1.1). Do you want a link to the generated code in .wgsl format right now?

**Comment by zeritonius** [comment]
I wll wait for that tutorial. Thank you for the info.

**Comment by Ryan-yang125** [comment]
> 

hi, you can find it in https://github.com/mlc-ai/web-llm/tree/gh-pages/docs/dist/vicuna-7b

**Comment by zeritonius** [comment]
@Ryan-yang125 
At the above location, I found the compiled file | the executable (.wasm), but not the text file | the source file (.wat). Do I need a special kind of access to see the .wat file?

Thank you.

**Comment by jinhongyii** [comment]
Thanks for your patience. We've just added an instruction for building models and deploy locally. Feel free to check it out. The wasm file you want will be under dist/vicuna-7b-v1 after running build.py

**Comment by jinhongyii** [comment]
Additional info to get source code, run 
```
python3 build.py --target webgpu --debug-dump
```
you will see the IR and wgsl file under dist/vicuna-7b-v1/debug
