### ISSUE TITLE
Where is the big vicuna-7b-v0 model file in local computer for chrome loading?

### ISSUE THREAD

**Issue by eatcosmos** [mlc-ai/web-llm#44]
Have run well with GPU Intel(R) Iris(R) Xe Graphics 8G.

I want to see what the model like:

I search by file size or file keywords(pkl model wgsl) through the whole computer drivers,
still cannot find the vicuna-7b-v0 model.
I also search through the code by keywords like save、model，can not find where save downloaded file params_shard_1.bin...

It's strange, where is the model file and which code deal with the model file and save them to computer drivers for chrome?

---
![image](https://user-images.githubusercontent.com/83876321/233164828-e7b1d3cf-17bd-47b2-a30b-173d01725c30.png)

**Comment by yunghoy** [comment]
C:\Users\{YOUR_NAME}\AppData\Local\Google\Chrome SxS\User Data\Default\Service Worker\CacheStorage

**Comment by eatcosmos** [comment]
![image](https://user-images.githubusercontent.com/83876321/233374314-5df7f71d-cd9b-4ef7-a6a5-0c70547960d6.png)

**Comment by zeritonius** [comment]
@eatcosmos 

> I search by file size or file keywords(pkl model wgsl) through the whole computer drivers,

In similar situations, I search by date and see the most recently created files. I use Windwos 10 Home edition and [Agent Ransack](https://www.mythicsoft.com/agentransack/) (it's free) which allows me to search what was created in the current day only.

If you want to see clean filenames (instead of random ones), here's what worked for me (plus, you can download them to a location you specify):
https://github.com/mlc-ai/web-llm/issues/19#issuecomment-1511754031
