### ISSUE TITLE
Sending raw text to the model

### ISSUE THREAD

**Issue by loristns** [mlc-ai/web-llm#507]
Hi there,
I'm developing an autocomplete app using `web-llm`, but I'm having trouble injecting my own raw prompt with control tokens bypassing the preconfigured chat conversation template. I have tried several methods, but it always seems like the lib is injecting control tokens into the LLM. I'm wondering if there is a way to send raw text to the model and get a completion without relying on high-level chat APIs?

I'm trying to achieve something like this:
```js
const prompt = `
<|start_header_id|>system<|end_header_id|>
You are a friendly assistant
<|eot_id|>
<|start_header_id|>user<|end_header_id|>
What's 2+2
<|eot_id|>
<|start_header_id|>assistant<|end_header_id|>
`;

const stop = '<|eot_id|>';
const reply = await engine.completion(prompt, stop);
// "The answer is 2+2=4"
```

Thanks 😅

**Comment by CharlieFRuan** [comment]
Hi! Raw text completion is supported in npm 0.2.56 via `engine.completions.create()`. See https://github.com/mlc-ai/web-llm/pull/534 for more! This should ignore everything except the stop tokens and stop strings in `mlc-chat-config.json`. You can override `mlc-chat-config.json` with `ChatOptions`, and override the conversation template with `ChatConfig.conv_config`.

**Comment by CharlieFRuan** [comment]
It may help for debug to add `console.log(prompts)` and `console.log(tokens)` here: https://github.com/mlc-ai/web-llm/blob/41e786b3f4097c165b1fc109b1b9317ed3193089/src/llm_chat.ts#L978

This is the exact string and tokens fed into the model, after applying any chat template. But this requires you to build WebLLM from source, which may take more work than other TS/JS packages due to dependency to TVMjs (will fix this soon): https://github.com/mlc-ai/web-llm?tab=readme-ov-file#build-webllm-package-from-source

**Comment by loristns** [comment]
Thank you for adding this feature!
